<style>
    .breadcrumb > li + li:before {
     content: "\00BB";
     color: #aaa;
}
</style>
<ul class="breadcrumb">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            
            // if this isn't the last page, add a link and the separator
            if ($key < count($this->pages) - 1):
                ?>
            <a  class="<?php echo $page->get("icon") ;?>" href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            <?php
            // otherwise, just output the name
            else:
            ?>
            <span  class="<?php echo $page->get("icon") ;?>"><?php echo $page->getLabel(); ?></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>


