-- MySQL Workbench Synchronization
-- Generated: 2015-12-09 10:46
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Marcelo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `sch`.`Controller` (
  `IDCONTROLLER` INT(11) NOT NULL COMMENT '',
  `NOME` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`IDCONTROLLER`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `sch`.`VIEW` (
  `IDVIEW` INT(11) NOT NULL COMMENT '',
  `Controller_IDCONTROLLER` INT(11) NOT NULL COMMENT '',
  `NOME` VARCHAR(45) NOT NULL COMMENT '',
  `LABEL` VARCHAR(45) NOT NULL COMMENT '',
  `ROUTE` VARCHAR(45) NOT NULL COMMENT '',
  `STATUS` INT(1) NOT NULL COMMENT '1 - Ativo\n2 - Inativo',
  PRIMARY KEY (`IDVIEW`)  COMMENT '',
  INDEX `fk_VIEW_Controller_idx` (`Controller_IDCONTROLLER` ASC)  COMMENT '',
  CONSTRAINT `fk_VIEW_Controller`
    FOREIGN KEY (`Controller_IDCONTROLLER`)
    REFERENCES `sch`.`Controller` (`IDCONTROLLER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

DROP TABLE IF EXISTS `sch`.`usuario` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
